pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh(script: "dotnet publish /var/lib/jenkins/workspace/EtsyBusinessMetricsAPI_dev/EtsyBusinessMetricsAPI.sln", returnStdout: true)
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: '/var/lib/jenkins/workspace/EtsyBusinessMetricsAPI_dev/EtsyBusinessMetricsAPI/bin/Release/net6.0/*.exe',
            onlyIfSuccessful: true
            cleanWs()
        }
    }
}
