pipeline {
    agent any

    stages {
       stage('NuGet Restore') {
            steps {
                sh(script: "nuget restore /var/lib/jenkins/workspace/EtsyBusinessMetricsAPI_dev/EtsyBusinessMetricsAPI.sln", returnStdout: true)
            }
        }
        stage('Build') {
            steps {
                sh(script: "dotnet build /var/lib/jenkins/workspace/EtsyBusinessMetricsAPI_dev/EtsyBusinessMetricsAPI.sln", returnStdout: true)
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: '**/*.dll.*', onlyIfSuccessful: true
        }
    }
}
